version: '3'
services:
  server:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./models:/root/.keras/models/
  nginx:
    image: nginx
    volumes:
      - ./static:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - server
    ports:
      - 8080:80